se is nu ru et tgc sc hls cin cino+=j1 sw=4 sts=4 bs=2 mouse=a "encoding=utf-8 ls=2
syn on | colo desert | filetype indent on
map <leader>b <ESC>:w<CR>:!g++ "%" -o "%<" -g -std=gnu++20 -DCKISEKI -Wall -Wextra -Wshadow -Wfatal-errors -Wconversion -fsanitize=address,undefined,float-divide-by-zero,float-cast-overflow && echo success<CR>
map <leader>z <ESC>:w<CR>:!g++ "%" -o "%<" -O2 -g -std=gnu++20 && echo success<CR>
map <leader>i <ESC>:!./"%<"<CR>
map <leader>r <ESC>:!cat 01.in && echo "---" && ./"%<" < 01.in<CR>
map <leader>l :%d<bar>0r ~/t.cpp<CR>
ca Hash w !cpp -dD -P -fpreprocessed \| tr -d "[:space:]" \| md5sum \| cut -c-6
let c_no_curly_error=1
